# python/src/utils/data_processing.py
import os
import numpy as np
import pandas as pd
import numba
import time
from numba import njit
from src.config import EnvConfig, SimConfig
from matio import load_from_mat
import itertools

# ==============================================================================
# 1. HIGH-LEVEL INGESTION & FLEET CACHING PIPELINE
# ==============================================================================

def load_and_interpolate_sov_data(file_paths: list[str], scale_factor: float = 0.75) -> dict:
    """
    Ingests raw .mat files for the Service Operation Vessel (SOV), combines them,
    sums the active generator powers, scales by scale_factor, and interpolates onto a 1 Hz grid.
    Defensively unpacks cell-wrapped arrays generated by matio table mapping.
    """
    t_c = []
    Pd_c = []
    t0_offset = 0.0
    
    generator_columns = [
        'DG1_GeneratorActivePower',
        'DG2_GeneratorActivePower',
        'DG3_GeneratorActivePower',
        'DG4_GeneratorActivePower'
    ]
    
    for path in file_paths:
        if not os.path.exists(path):
            raise FileNotFoundError(f"Vessel data file not found at: {path}")
            
        mat_contents = load_from_mat(path, raw_data=False)
        raw_data = mat_contents['SOV_data']  
        
        def _clean_string(x) -> str:
            if isinstance(x, np.ndarray):
                x = x.item() if x.size == 1 else x.flatten()[0]
            if isinstance(x, bytes):
                return x.decode('utf-8').strip()
            return str(x).strip()

        def _clean_float(x) -> float:
            if isinstance(x, np.ndarray):
                return float(x.item() if x.size == 1 else x.flatten()[0])
            return float(x)
        
        timestamps = [_clean_string(val) for val in raw_data['Timestamp_UTC_']]
        dates = pd.to_datetime(timestamps, format='mixed')
        elapsed_seconds = (dates - dates[0]).total_seconds().to_numpy()
        
        power_matrix = np.zeros((len(dates), len(generator_columns)))
        for col_idx, col in enumerate(generator_columns):
            power_matrix[:, col_idx] = [_clean_float(val) for val in raw_data[col]]
            
        # --- SCALE DEMAND PROFILE HERE ---
        power_demand = np.sum(power_matrix, axis=1) * scale_factor
        
        t_target = np.arange(0, int(elapsed_seconds[-1]) + 1, dtype=np.float64)
        power_interp = np.interp(t_target, elapsed_seconds, power_demand)
        
        t_c.append(t_target + t0_offset)
        Pd_c.append(power_interp)
        t0_offset = t_c[-1][-1]
        
    return {
        't': np.concatenate(t_c),
        'Pd': np.concatenate(Pd_c)
    }


def load_and_cache_entire_fleet(config: EnvConfig) -> dict[int, dict]:
    """
    Executes disk I/O to cache all available days (1-14) in RAM.
    Uses a compressed binary .npz file tagged with the scale factor.
    """
    # 1. Fetch scale factor from EnvConfig or default to 0.75
    scale_factor = getattr(config, 'power_scale_factor', 0.75)
    
    # Tag cache path with scale factor so changed scales force re-parsing
    cache_filename = f"fleet_data_cache_scale_{scale_factor:.2f}.npz"
    cache_path = os.path.join(config.cache_dir, cache_filename)
    
    # --- STAGE 1: Try to load from the binary cache ---
    if os.path.exists(cache_path):
        print(f"Loading fleet data from binary cache ({cache_filename})...")
        start_t = time.perf_counter()
        fleet_cache = {}
        
        with np.load(cache_path) as data:
            for file_key in data.files:
                parts = file_key.split('_')
                day_num = int(parts[1])
                var_name = parts[2]  # 't' or 'Pd'
                
                if day_num not in fleet_cache:
                    fleet_cache[day_num] = {}
                fleet_cache[day_num][var_name] = data[file_key]
                
        print(f" -> Cache instantly loaded in {time.perf_counter() - start_t:.3f} seconds.")
        return fleet_cache

    # --- STAGE 2: If no cache exists, parse raw .mat files ---
    fleet_cache = {}
    dir_path = config.data_dir
    all_fleet_files = [f"{dir_path}/SOV_{day:02d}-Feb-2023.mat" for day in range(1, 15)]
    
    print(f"Binary cache not found. Parsing raw .mat files with scale_factor={scale_factor}...")
    for idx, path in enumerate(all_fleet_files):
        day_num = idx + 1
        if os.path.exists(path):
            fleet_cache[day_num] = load_and_interpolate_sov_data([path], scale_factor=scale_factor)
            print(f" -> Day {day_num:02d} successfully parsed and scaled.")
        else:
            # Fallback mock data with scaling
            print(f" [!] File not found at {path}. Generating fallback numerical profile for Day {day_num:02d}...")
            t_mock = np.arange(0, 86400, dtype=np.float64)
            pd_mock = (600.0 + 200.0 * np.sin(2 * np.pi * t_mock / 86400) + np.random.normal(0, 30, len(t_mock))) * scale_factor
            fleet_cache[day_num] = {'t': t_mock, 'Pd': pd_mock}
            
    # --- STAGE 3: Save to binary cache ---
    print(f"Compressing and writing data to {cache_filename}...")
    save_dict = {}
    for day_num, data_dict in fleet_cache.items():
        save_dict[f"day_{day_num}_t"] = data_dict['t']
        save_dict[f"day_{day_num}_Pd"] = data_dict['Pd']

    cache_dir = os.path.dirname(cache_path)
    os.makedirs(cache_dir, exist_ok=True)
        
    np.savez_compressed(cache_path, **save_dict)
    print("All operational days scaled, cached in RAM, and written to disk.")
    
    return fleet_cache


def calibrate_markov_chain(data_dict: dict, config: SimConfig, manual_edges=None) -> dict:
    """Standard orchestration routine for single continuous data sets."""
    ds_data = downsample_block_mean(data_dict['t'], data_dict['Pd'], config.delta_t, align='t0')
    mc_model = fit_dtmc(ds_data['Pd'], config.N_pd, config.alpha_mc, manual_edges=manual_edges)
    mc_model['Delta'] = config.delta_t  
    return mc_model

# ==============================================================================
# 2. NUMBA-ACCELERATED MATHEMATICAL ROUTINES (Segment-Aware Shell/Worker Pattern)
# ==============================================================================

@njit(cache=True)
def _qsimple_numba(x: np.ndarray, p: float) -> float:
    n = len(x)
    r = (n - 1) * p
    i = int(np.floor(r))
    j = int(np.ceil(r))
    if i == j:
        return x[max(0, min(n - 1, i))]
    w = r - i
    return (1.0 - w) * x[i] + w * x[j]


@njit(cache=True)
def _make_edges_quantile_numba(x: np.ndarray, m_states: int) -> np.ndarray:
    valid_mask = np.isfinite(x)
    x_filtered = x[valid_mask]
    x_sorted = np.sort(x_filtered)
    qs = np.linspace(0.0, 1.0, m_states + 1)
    edges = np.zeros(m_states + 1)
    for idx in range(m_states + 1):
        edges[idx] = _qsimple_numba(x_sorted, qs[idx])
    edges[0] = min(x_sorted[0], edges[0]) - np.spacing(edges[0])
    edges[-1] = max(x_sorted[-1], edges[-1]) + np.spacing(edges[-1])
    
    unique_count = 1
    for i in range(1, len(edges)):
        if edges[i] != edges[i-1]:
            unique_count += 1
    if unique_count < m_states + 1:
        edges = np.linspace(x_sorted[0], x_sorted[-1], m_states + 1)
    return edges


@njit(cache=True)
def _downsample_block_mean_worker(t: np.ndarray, y: np.ndarray, t_sec: int, align_t0: bool):
    valid_mask = np.isfinite(t) & np.isfinite(y)
    t_v = t[valid_mask]
    y_v = y[valid_mask]
    sort_idx = np.argsort(t_v)
    t_s = t_v[sort_idx]
    y_s = y_v[sort_idx]
    
    if align_t0:
        t0 = t_s[0]
    else:
        t0 = np.floor(t_s[0] / t_sec) * t_sec
        
    b = np.floor((t_s - t0) / t_sec).astype(np.int32)
    bmin, bmax = b[0], b[-1]
    nb = bmax - bmin + 1
    sumy, cnt = np.zeros(nb), np.zeros(nb)
    
    for idx in range(len(b)):
        bin_id = b[idx] - bmin
        sumy[bin_id] += y_s[idx]
        cnt[bin_id] += 1.0
        
    tL = t0 + (np.arange(bmin, bmax + 1)) * t_sec
    keep = cnt > 0
    return tL[keep] + t_sec / 2.0, sumy[keep] / cnt[keep], tL[keep]


def downsample_block_mean(t: np.ndarray, y: np.ndarray, t_sec: int, align: str = 't0') -> dict:
    align_t0 = (align == 't0')
    t_center, pd_mean, left_edges = _downsample_block_mean_worker(t, y, t_sec, align_t0)
    return {'t': t_center, 'Pd': pd_mean, 'left_edges': left_edges, 'Tsec': t_sec}


@njit(cache=True)
def _fit_dtmc_worker(segments: numba.typed.List, m_states: int, alpha: float, edges: np.ndarray):
    """
    Private JIT-compiled multi-segment validation kernel.
    Edges are now injected to support manual grid resolution overrides.
    """
    N = np.zeros((m_states, m_states), dtype=np.float64)
    for seg in segments:
        if len(seg) < 2:
            continue
        S = np.zeros(len(seg), dtype=np.int32)
        for idx in range(len(seg)):
            val = seg[idx]
            bin_idx = m_states - 1
            for b_idx in range(m_states):
                if val >= edges[b_idx] and val < edges[b_idx+1]:
                    bin_idx = b_idx
                    break
            S[idx] = bin_idx
            
        for idx in range(len(S) - 1):
            N[S[idx], S[idx+1]] += 1.0
            
    P = N + alpha
    for r_idx in range(m_states):
        row_sum = np.sum(P[r_idx, :])
        if row_sum == 0:
            P[r_idx, :] = 1.0 / m_states
        else:
            P[r_idx, :] = P[r_idx, :] / row_sum
            
    A = np.zeros((m_states + 1, m_states))
    A[:m_states, :] = P.T - np.eye(m_states)
    A[m_states, :] = 1.0
    b_vec = np.zeros(m_states + 1)
    b_vec[m_states] = 1.0
    
    ATA = A.T @ A
    ATb = A.T @ b_vec
    stationary_pi = np.linalg.solve(ATA, ATb)
    
    levels = np.zeros(m_states)
    for idx in range(m_states):
        levels[idx] = (edges[idx] + edges[idx+1]) / 2.0
        
    return P, N, stationary_pi, levels


def fit_dtmc(power_samples, m_states: int, alpha: float = 0.5, manual_edges: np.ndarray = None, manual_levels: np.ndarray = None) -> dict:
    """
    Public segment-aware interface. 
    Accepts manual_edges and manual_levels to override automatic binning.
    """
    numba_list = numba.typed.List()
    total_len = 0
    if isinstance(power_samples, np.ndarray):
        flat_samples = power_samples.flatten()
        numba_list.append(flat_samples)
        total_len += len(flat_samples)
    elif isinstance(power_samples, list):
        for seg in power_samples:
            flat_samples = seg.flatten()
            numba_list.append(flat_samples)
            total_len += len(flat_samples)
    else:
        raise TypeError("power_samples must be an ndarray or list of ndarrays")
        
    if manual_edges is not None:
        edges = np.array(manual_edges, dtype=np.float64)
        m_states = len(edges) - 1
    else:
        all_samples = np.zeros(total_len, dtype=np.float64)
        cursor = 0
        for seg in numba_list:
            all_samples[cursor:cursor+len(seg)] = seg
            cursor += len(seg)
        edges = _make_edges_quantile_numba(all_samples, m_states)
        
    P, N, stationary_pi, levels = _fit_dtmc_worker(numba_list, m_states, alpha, edges)
    
    # NEW: Override the midpoints if specific physical grid nodes were requested
    if manual_levels is not None:
        levels = np.array(manual_levels, dtype=np.float64)
        
    return {'P': P, 'N': N, 'pi': stationary_pi, 'edges': edges, 'levels': levels}


@njit(cache=True)
def _find_optimal_lattice_subset(ideal_nodes: np.ndarray, lattice: np.ndarray) -> np.ndarray:
    """
    Uses Dynamic Programming to find the exact optimal subset of 'lattice' 
    that minimizes the Mean Squared Quantization Error to 'ideal_nodes'.
    """
    K = len(ideal_nodes)
    N = len(lattice)
    
    # dp[n, k] = min squared error matching first k ideal nodes using a subset of first n lattice nodes
    dp = np.full((N + 1, K + 1), np.inf)
    choice = np.zeros((N + 1, K + 1), dtype=np.int32)
    
    # Base case: 0 error to match 0 nodes
    for n in range(N + 1):
        dp[n, 0] = 0.0
        
    for n in range(1, N + 1):
        for k in range(1, K + 1):
            if k > n:
                continue # Impossible to match k items with fewer than k lattice nodes
            
            cost_skip = dp[n - 1, k]
            cost_use = dp[n - 1, k - 1] + (ideal_nodes[k - 1] - lattice[n - 1])**2
            
            if cost_use < cost_skip:
                dp[n, k] = cost_use
                choice[n, k] = 1 
            else:
                dp[n, k] = cost_skip
                choice[n, k] = 0 
                
    # Backtrack to reconstruct the optimal grid
    optimal_grid = np.zeros(K, dtype=np.float64)
    n, k = N, K
    while k > 0:
        if choice[n, k] == 1:
            optimal_grid[k - 1] = lattice[n - 1]
            k -= 1
            n -= 1
        else:
            n -= 1
            
    return optimal_grid

@njit(cache=True)
def _optimize_lattice_dp_worker(X: np.ndarray, W: np.ndarray, C: np.ndarray, K: int):
    """
    JIT-compiled Bellman Recursion for 1D Optimal Discrete Quantization.
    Minimizes the Mean Squared Quantization Error (MSQE) over the rigid lattice.
    """
    M = len(C)
    
    # 1. Precompute MSQE costs for all possible segments between two chosen nodes
    cost_mat = np.zeros((M, M))
    for i in range(M):
        for j in range(i + 1, M):
            mid = (C[i] + C[j]) / 2.0
            err = 0.0
            for m in range(len(X)):
                if C[i] <= X[m] < mid:
                    err += W[m] * (X[m] - C[i])**2
                elif mid <= X[m] <= C[j]:
                    err += W[m] * (X[m] - C[j])**2
            cost_mat[i, j] = err
            
    # 2. Precompute prefix (left tail) and suffix (right tail) costs
    prefix = np.zeros(M)
    suffix = np.zeros(M)
    for i in range(M):
        err_pref = 0.0
        err_suff = 0.0
        for m in range(len(X)):
            if X[m] < C[i]:
                err_pref += W[m] * (X[m] - C[i])**2
            if X[m] > C[i]:
                err_suff += W[m] * (X[m] - C[i])**2
        prefix[i] = err_pref
        suffix[i] = err_suff

    # 3. Initialize Bellman DP Table
    # dp[k, j] = min cost to place k nodes, rightmost node ending at index j
    dp = np.full((K + 1, M), np.inf)
    choice = np.zeros((K + 1, M), dtype=np.int32)
    
    # Base case k = 1
    for j in range(M):
        dp[1, j] = prefix[j]
        
    # Recursive step: Forward Induction
    for k in range(2, K + 1):
        for j in range(k - 1, M): 
            best_cost = np.inf
            best_i = -1
            for i in range(k - 2, j): 
                cost = dp[k - 1, i] + cost_mat[i, j]
                if cost < best_cost:
                    best_cost = cost
                    best_i = i
            dp[k, j] = best_cost
            choice[k, j] = best_i
            
    # 4. Find the optimal terminal node (Kth node)
    best_total = np.inf
    best_last_j = -1
    for j in range(K - 1, M):
        total = dp[K, j] + suffix[j]
        if total < best_total:
            best_total = total
            best_last_j = j
            
    # 5. Backtrack to recover the optimal lattice subset
    selected_indices = np.zeros(K, dtype=np.int32)
    curr_j = best_last_j
    for k in range(K, 0, -1):
        selected_indices[k - 1] = curr_j
        curr_j = choice[k, curr_j]
        
    return selected_indices

def generate_geometric_lattice_dp(data: np.ndarray, delta_P: float, N_d: int):
    """
    Public wrapper for the Geometric (MSQE) Bellman Grid Optimizer.
    """
    # 1. High-Resolution Data Binning (Reduces O(N) evaluation to O(1) histogram lookup)
    fine_edges = np.arange(0, np.max(data) + delta_P, 1.0)
    fine_mids = (fine_edges[:-1] + fine_edges[1:])/2.0
    hist, _ = np.histogram(data, bins=fine_edges)

    active_mask = hist > 0
    X = fine_mids[active_mask]
    W = hist[active_mask]

    # 2. Extract FULL Physical Lattice Candidates
    max_lattice_val = max(np.max(data) + delta_P, N_d * delta_P)
    C = np.arange(0.0, max_lattice_val + (delta_P / 2.0), delta_P)
    
    # Safety catch
    if N_d >= len(C):
        smart_levels = C[:N_d]
    else:
        # 3. Execute Numba DP
        selected_indices = _optimize_lattice_dp_worker(X, W, C, N_d)
        smart_levels = C[selected_indices]

    # 4. Voronoi Edge Generation
    smart_edges = np.zeros(N_d + 1)
    smart_edges[0] = -1e-3
    smart_edges[-1] = max(np.max(data) + delta_P, smart_levels[-1] + delta_P)
    for idx in range(1, N_d):
        smart_edges[idx] = (smart_levels[idx-1] + smart_levels[idx]) / 2.0

    return smart_levels, smart_edges


def generate_frequency_lattice(data_array: np.ndarray, delta_P: float, m_states: int):
    """ Empirical Frequency Projection. """
    snapped_data = np.round(data_array / delta_P) * delta_P
    unique_vals, counts = np.unique(snapped_data, return_counts=True)
    
    top_k = min(m_states, len(unique_vals))
    top_indices = np.argsort(-counts)[:top_k]
    smart_levels = np.sort(unique_vals[top_indices])

    # CRITICAL FIX: Guarantee exactly m_states cardinality
    # If the data is extremely flat and occupies fewer than m_states unique nodes, 
    # we must pad the state space to prevent the Markov matrix from shrinking and crashing the SDP.
    if len(smart_levels) < m_states:
        max_val = max(np.max(data_array) + delta_P, m_states * delta_P)
        full_lattice = np.arange(0.0, max_val + (delta_P / 2.0), delta_P)
        unused = np.setdiff1d(full_lattice, smart_levels)
        missing = m_states - len(smart_levels)
        smart_levels = np.sort(np.concatenate([smart_levels, unused[:missing]]))

    smart_edges = np.zeros(m_states + 1)
    smart_edges[0] = -1e-3
    smart_edges[-1] = max(np.max(data_array) + delta_P, smart_levels[-1] + delta_P)
    for idx in range(1, m_states):
        smart_edges[idx] = (smart_levels[idx-1] + smart_levels[idx]) / 2.0
        
    return smart_levels, smart_edges

def optimize_lattice_combinations(data: np.ndarray, delta_P: float, N_d: int, method='mass_variance'):
    """ Combinatorial Optimizer for the rigid delta_P lattice (Used for Mass Variance). """
    fine_edges = np.arange(0, np.max(data) + delta_P, 1.0)
    fine_mids = (fine_edges[:-1] + fine_edges[1:])/2.0
    hist, _ = np.histogram(data, bins=fine_edges)

    active_mask = hist > 0
    active_mids = fine_mids[active_mask]
    active_hist = hist[active_mask]
    total_pts = np.sum(active_hist)
    ideal_mass = 1.0 / N_d

    snapped = np.round(data / delta_P) * delta_P
    unique_vals, counts = np.unique(snapped, return_counts=True)
    top_indices = np.argsort(-counts)[:min(25, len(unique_vals))]
    candidates = np.sort(unique_vals[top_indices])

    if len(candidates) < N_d:
        candidates = np.arange(0, N_d * delta_P, delta_P)

    best_cost = np.inf
    best_subset = None

    for subset in itertools.combinations(candidates, N_d):
        subset_arr = np.array(subset)
        diffs = np.abs(active_mids[:, None] - subset_arr[None, :])
        nearest_idx = np.argmin(diffs, axis=1)

        if method == 'mass_variance':
            bin_counts = np.bincount(nearest_idx, weights=active_hist, minlength=N_d)
            masses = bin_counts / total_pts
            cost = np.sum((masses - ideal_mass)**2)
        else:
            # Fallback for geometric if combinatorial is requested
            min_diffs = np.min(diffs, axis=1)
            cost = np.sum(active_hist * (min_diffs**2))

        if cost < best_cost:
            best_cost = cost
            best_subset = subset_arr

    smart_levels = np.sort(best_subset)
    smart_edges = np.zeros(N_d + 1)
    smart_edges[0] = -1e-3
    smart_edges[-1] = max(np.max(data) + delta_P, smart_levels[-1] + delta_P)
    for idx in range(1, N_d):
        smart_edges[idx] = (smart_levels[idx-1] + smart_levels[idx]) / 2.0

    return smart_levels, smart_edges

def generate_demand_grid(data: np.ndarray, delta_P: float, N_d: int, method: str = 'geometric'):
    """
    Master Router for Grid Generation. 
    Routes to the appropriate topology algorithm.
    """
    min_observed = np.min(data)
    max_observed = np.max(data)
    
    # Generate the physical hardware lattice
    max_lattice_val = max(max_observed + delta_P, N_d * delta_P)
    full_lattice = np.arange(0.0, max_lattice_val + (delta_P / 2.0), delta_P)

    if method == 'geometric':
        # Blazing fast Bellman Recursion
        return generate_geometric_lattice_dp(data, delta_P, N_d)
        
    elif method == 'frequency':
        # Empirical frequency (now padded to guarantee N_d cardinality)
        return generate_frequency_lattice(data, delta_P, N_d)
        
    elif method == 'mass_variance':
        # Combinatorial search for uniform information density
        return optimize_lattice_combinations(data, delta_P, N_d, method='mass_variance')
        
    elif method == 'quantile':
        # Legacy Continuous Quantiles snapped to lattice
        legacy_edges = _make_edges_quantile_numba(data, N_d)
        ideal_levels = np.array([(legacy_edges[i] + legacy_edges[i+1])/2.0 for i in range(N_d)])
        levels = _find_optimal_lattice_subset(ideal_levels, full_lattice)
        
    elif method == 'linear':
        # FIXED: Naive linear spacing bounds updated to min/max observed
        ideal_edges = np.linspace(min_observed, max_observed, N_d + 1)
        ideal_levels = (ideal_edges[:-1] + ideal_edges[1:]) / 2.0
        levels = _find_optimal_lattice_subset(ideal_levels, full_lattice)
        
    else:
        raise ValueError(f"Unknown grid method requested: {method}")

    # Common Voronoi Edge Generation for snapped targets (Quantile & Linear)
    edges = np.zeros(N_d + 1)
    edges[0] = -1e-3
    # Safer upper bound to encapsulate data without overextending artificially
    edges[-1] = max(max_observed + delta_P, levels[-1] + delta_P) 
    for idx in range(1, N_d):
        edges[idx] = (levels[idx-1] + levels[idx]) / 2.0
        
    return levels, edges