# python/src/data_processing.py
import os
import numpy as np
import pandas as pd
import numba
from numba import njit
from config import SimConfig
from matio import load_from_mat

# ==============================================================================
# 1. HIGH-LEVEL INGESTION & FLEET CACHING PIPELINE
# ==============================================================================

def load_and_interpolate_sov_data(file_paths: list[str]) -> dict:
    """
    Ingests raw .mat files for the Service Operation Vessel (SOV), combines them,
    sums the active generator powers, and interpolates onto a 1 Hz grid.
    Defensively unpacks cell-wrapped arrays generated by matio table mapping.
    """
    t_c = []
    Pd_c = []
    t0_offset = 0.0
    
    generator_columns = [
        'DG1_GeneratorActivePower',
        'DG2_GeneratorActivePower',
        'DG3_GeneratorActivePower',
        'DG4_GeneratorActivePower'
    ]
    
    for path in file_paths:
        if not os.path.exists(path):
            raise FileNotFoundError(f"Vessel data file not found at: {path}")
            
        mat_contents = load_from_mat(path, raw_data=False)
        raw_data = mat_contents['SOV_data']  
        
        def _clean_string(x) -> str:
            if isinstance(x, np.ndarray):
                x = x.item() if x.size == 1 else x.flatten()[0]
            if isinstance(x, bytes):
                return x.decode('utf-8').strip()
            return str(x).strip()

        def _clean_float(x) -> float:
            if isinstance(x, np.ndarray):
                return float(x.item() if x.size == 1 else x.flatten()[0])
            return float(x)
        
        timestamps = [_clean_string(val) for val in raw_data['Timestamp_UTC_']]
        dates = pd.to_datetime(timestamps, format='mixed')
        elapsed_seconds = (dates - dates[0]).total_seconds().to_numpy()
        
        power_matrix = np.zeros((len(dates), len(generator_columns)))
        for col_idx, col in enumerate(generator_columns):
            power_matrix[:, col_idx] = [_clean_float(val) for val in raw_data[col]]
            
        power_demand = np.sum(power_matrix, axis=1)
        t_target = np.arange(0, int(elapsed_seconds[-1]) + 1, dtype=np.float64)
        power_interp = np.interp(t_target, elapsed_seconds, power_demand)
        
        t_c.append(t_target + t0_offset)
        Pd_c.append(power_interp)
        t0_offset = t_c[-1][-1]
        
    return {
        't': np.concatenate(t_c),
        'Pd': np.concatenate(Pd_c)
    }


def load_and_cache_entire_fleet() -> dict[int, dict]:
    """
    Executes disk I/O exactly once to cache all available days (1-14) in RAM.
    Falls back gracefully to mock data if specific file frames are missing.
    """
    fleet_cache = {}
    all_fleet_files = [f"../data/SOV_{day:02d}-Feb-2023.mat" for day in range(1, 15)]
    
    print("Beginning memory staging of all 14 fleet files into RAM...")
    for idx, path in enumerate(all_fleet_files):
        day_num = idx + 1
        if os.path.exists(path):
            fleet_cache[day_num] = load_and_interpolate_sov_data([path])
            print(f" -> Day {day_num:02d} successfully cached in RAM.")
        else:
            # Graceful fallback configuration for local environments missing certain days
            print(f" [!] File not found at {path}. Generating fallback numerical profile for Day {day_num:02d}...")
            t_mock = np.arange(0, 86400, dtype=np.float64)
            pd_mock = 600.0 + 200.0 * np.sin(2 * np.pi * t_mock / 86400) + np.random.normal(0, 30, len(t_mock))
            fleet_cache[day_num] = {'t': t_mock, 'Pd': pd_mock}
            
    print("\nAll 14 operational days securely held in RAM. Disk I/O locked.")
    return fleet_cache


def calibrate_markov_chain(data_dict: dict, config: SimConfig) -> dict:
    """Standard orchestration routine for single continuous data sets."""
    ds_data = downsample_block_mean(data_dict['t'], data_dict['Pd'], config.Ts, align='t0')
    mc_model = fit_dtmc(ds_data['Pd'], config.n_states, config.alpha)
    mc_model['Delta'] = config.Ts  
    return mc_model

# ==============================================================================
# 2. NUMBA-ACCELERATED MATHEMATICAL ROUTINES (Segment-Aware Shell/Worker Pattern)
# ==============================================================================

@njit(cache=True)
def _qsimple_numba(x: np.ndarray, p: float) -> float:
    n = len(x)
    r = (n - 1) * p
    i = int(np.floor(r))
    j = int(np.ceil(r))
    if i == j:
        return x[max(0, min(n - 1, i))]
    w = r - i
    return (1.0 - w) * x[i] + w * x[j]


@njit(cache=True)
def _make_edges_quantile_numba(x: np.ndarray, m_states: int) -> np.ndarray:
    valid_mask = np.isfinite(x)
    x_filtered = x[valid_mask]
    x_sorted = np.sort(x_filtered)
    qs = np.linspace(0.0, 1.0, m_states + 1)
    edges = np.zeros(m_states + 1)
    for idx in range(m_states + 1):
        edges[idx] = _qsimple_numba(x_sorted, qs[idx])
    edges[0] = min(x_sorted[0], edges[0]) - np.spacing(edges[0])
    edges[-1] = max(x_sorted[-1], edges[-1]) + np.spacing(edges[-1])
    
    unique_count = 1
    for i in range(1, len(edges)):
        if edges[i] != edges[i-1]:
            unique_count += 1
    if unique_count < m_states + 1:
        edges = np.linspace(x_sorted[0], x_sorted[-1], m_states + 1)
    return edges


@njit(cache=True)
def _downsample_block_mean_worker(t: np.ndarray, y: np.ndarray, t_sec: int, align_t0: bool):
    valid_mask = np.isfinite(t) & np.isfinite(y)
    t_v = t[valid_mask]
    y_v = y[valid_mask]
    sort_idx = np.argsort(t_v)
    t_s = t_v[sort_idx]
    y_s = y_v[sort_idx]
    
    if align_t0:
        t0 = t_s[0]
    else:
        t0 = np.floor(t_s[0] / t_sec) * t_sec
        
    b = np.floor((t_s - t0) / t_sec).astype(np.int32)
    bmin, bmax = b[0], b[-1]
    nb = bmax - bmin + 1
    sumy, cnt = np.zeros(nb), np.zeros(nb)
    
    for idx in range(len(b)):
        bin_id = b[idx] - bmin
        sumy[bin_id] += y_s[idx]
        cnt[bin_id] += 1.0
        
    tL = t0 + (np.arange(bmin, bmax + 1)) * t_sec
    keep = cnt > 0
    return tL[keep] + t_sec / 2.0, sumy[keep] / cnt[keep], tL[keep]


def downsample_block_mean(t: np.ndarray, y: np.ndarray, t_sec: int, align: str = 't0') -> dict:
    align_t0 = (align == 't0')
    t_center, pd_mean, left_edges = _downsample_block_mean_worker(t, y, t_sec, align_t0)
    return {'t': t_center, 'Pd': pd_mean, 'left_edges': left_edges, 'Tsec': t_sec}


@njit(cache=True)
def _fit_dtmc_worker(segments: numba.typed.List, m_states: int, alpha: float, 
                     use_precomputed: bool, precomp_edges: np.ndarray):
    """
    Private JIT-compiled multi-segment validation kernel.
    Accumulates transitions segment-by-segment to prevent midnight boundary errors.
    """
    total_len = 0
    for seg in segments:
        total_len += len(seg)
        
    all_samples = np.zeros(total_len, dtype=np.float64)
    cursor = 0
    for seg in segments:
        all_samples[cursor:cursor+len(seg)] = seg
        cursor += len(seg)
        
    if use_precomputed:
        edges = precomp_edges
    else:
        edges = _make_edges_quantile_numba(all_samples, m_states)
        
    N = np.zeros((m_states, m_states), dtype=np.float64)
    
    for seg in segments:
        if len(seg) < 2:
            continue
        S = np.zeros(len(seg), dtype=np.int32)
        for idx in range(len(seg)):
            val = seg[idx]
            bin_idx = m_states - 1
            for b_idx in range(m_states):
                if val >= edges[b_idx] and val < edges[b_idx+1]:
                    bin_idx = b_idx
                    break
            S[idx] = bin_idx
            
        for idx in range(len(S) - 1):
            N[S[idx], S[idx+1]] += 1.0
            
    P = N + alpha
    for r_idx in range(m_states):
        row_sum = np.sum(P[r_idx, :])
        if row_sum == 0:
            P[r_idx, :] = 1.0 / m_states
        else:
            P[r_idx, :] = P[r_idx, :] / row_sum
        
    A = np.zeros((m_states + 1, m_states))
    A[:m_states, :] = P.T - np.eye(m_states)
    A[m_states, :] = 1.0
    b_vec = np.zeros(m_states + 1)
    b_vec[m_states] = 1.0
    
    ATA = A.T @ A
    ATb = A.T @ b_vec
    stationary_pi = np.linalg.solve(ATA, ATb)
    
    levels = np.zeros(m_states)
    for idx in range(m_states):
        levels[idx] = (edges[idx] + edges[idx+1]) / 2.0
        
    return P, N, stationary_pi, edges, levels

def fit_dtmc(power_samples, m_states: int, alpha: float = 0.5, precomputed_edges: np.ndarray = None) -> dict:
    """Public wrapper handling the optional precomputed edges."""
    numba_list = numba.typed.List()
    if isinstance(power_samples, np.ndarray):
        numba_list.append(power_samples.flatten())
    elif isinstance(power_samples, list):
        for seg in power_samples:
            numba_list.append(seg.flatten())
    else:
        raise TypeError("power_samples must be an ndarray or list of ndarrays")
        
    use_precomp = (precomputed_edges is not None)
    # If no edges provided, pass a dummy array to keep Numba types consistent
    dummy_edges = precomputed_edges if use_precomp else np.zeros(m_states + 1, dtype=np.float64)
    
    P, N, stationary_pi, edges, levels = _fit_dtmc_worker(
        numba_list, m_states, alpha, use_precomp, dummy_edges
    )
    
    return {'P': P, 'N': N, 'pi': stationary_pi, 'edges': edges, 'levels': levels}
    return {'P': P, 'N': N, 'pi': stationary_pi, 'edges': edges, 'levels': levels}