# python/src/data_processing.py
import os
import numpy as np
import pandas as pd
from numba import njit
from config import SimConfig
from matio import load_from_mat

# ==============================================================================
# 1. HIGH-LEVEL INGESTION PIPELINE (Python / SciPy / Pandas)
# ==============================================================================

def load_and_interpolate_sov_data(file_paths: list[str]) -> dict:
    """
    Ingests raw .mat files for the Service Operation Vessel (SOV), combines them,
    sums the active generator powers, and interpolates onto a 1 Hz grid.
    Defensively unpacks cell-wrapped arrays generated by matio table mapping.
    """
    t_c = []
    Pd_c = []
    t0_offset = 0.0
    
    generator_columns = [
        'DG1_GeneratorActivePower',
        'DG2_GeneratorActivePower',
        'DG3_GeneratorActivePower',
        'DG4_GeneratorActivePower'
    ]
    
    for path in file_paths:
        if not os.path.exists(path):
            raise FileNotFoundError(f"Vessel data file not found at: {path}")
            
        mat_contents = load_from_mat(path, raw_data=False)
        raw_data = mat_contents['SOV_data']  
        
        def _clean_string(x) -> str:
            if isinstance(x, np.ndarray):
                x = x.item() if x.size == 1 else x.flatten()[0]
            if isinstance(x, bytes):
                return x.decode('utf-8').strip()
            return str(x).strip()

        def _clean_float(x) -> float:
            if isinstance(x, np.ndarray):
                return float(x.item() if x.size == 1 else x.flatten()[0])
            return float(x)
        
        timestamps = [_clean_string(val) for val in raw_data['Timestamp_UTC_']]
        dates = pd.to_datetime(timestamps, format='mixed')
        elapsed_seconds = (dates - dates[0]).total_seconds().to_numpy()
        
        power_matrix = np.zeros((len(dates), len(generator_columns)))
        for col_idx, col in enumerate(generator_columns):
            power_matrix[:, col_idx] = [_clean_float(val) for val in raw_data[col]]
            
        power_demand = np.sum(power_matrix, axis=1)
        t_target = np.arange(0, int(elapsed_seconds[-1]) + 1, dtype=np.float64)
        power_interp = np.interp(t_target, elapsed_seconds, power_demand)
        
        t_c.append(t_target + t0_offset)
        Pd_c.append(power_interp)
        t0_offset = t_c[-1][-1]
        
    return {
        't': np.concatenate(t_c),
        'Pd': np.concatenate(Pd_c)
    }


def calibrate_markov_chain(data_dict: dict, config: SimConfig) -> dict:
    """
    High-level orchestration routine to downsample continuous time-series data,
    discretize state spaces, and extract Markov parameters.
    """
    # Step A: Perform block-mean aggregation downsampling
    ds_data = downsample_block_mean(data_dict['t'], data_dict['Pd'], config.Ts, align='t0')
    
    # Step B: Fit the Discrete-Time Markov Chain parameters
    mc_model = fit_dtmc(ds_data['Pd'], config.n_states, config.alpha)
    mc_model['Delta'] = config.Ts  
    
    return mc_model


# ==============================================================================
# 2. NUMBA-ACCELERATED MATHEMATICAL ROUTINES (Decoupled Python-Shell / JIT-Worker Pattern)
# ==============================================================================

@njit(cache=True)
def _qsimple_numba(x: np.ndarray, p: float) -> float:
    """
    Numba port of the custom linear interpolation quantile estimator 'qsimple'.
    Adjusted precisely for 0-based array index offsets.
    """
    n = len(x)
    r = (n - 1) * p
    i = int(np.floor(r))
    j = int(np.ceil(r))
    
    if i == j:
        return x[max(0, min(n - 1, i))]
        
    w = r - i
    return (1.0 - w) * x[i] + w * x[j]


@njit(cache=True)
def _make_edges_quantile_numba(x: np.ndarray, m_states: int) -> np.ndarray:
    """
    Generates quantile-based grid bin edges without using external libraries.
    Matches the exact manual linear interpolation pipeline of make_edges_quantile.
    """
    valid_mask = np.isfinite(x)
    x_filtered = x[valid_mask]
    x_sorted = np.sort(x_filtered)
    
    qs = np.linspace(0.0, 1.0, m_states + 1)
    edges = np.zeros(m_states + 1)
    
    for idx in range(m_states + 1):
        edges[idx] = _qsimple_numba(x_sorted, qs[idx])
        
    edges[0] = min(x_sorted[0], edges[0]) - np.spacing(edges[0])
    edges[-1] = max(x_sorted[-1], edges[-1]) + np.spacing(edges[-1])
    
    unique_count = 1
    for i in range(1, len(edges)):
        if edges[i] != edges[i-1]:
            unique_count += 1
            
    if unique_count < m_states + 1:
        edges = np.linspace(x_sorted[0], x_sorted[-1], m_states + 1)
        
    return edges


@njit(cache=True)
def _downsample_block_mean_worker(t: np.ndarray, y: np.ndarray, t_sec: int, align_t0: bool):
    """
    Private JIT-compiled mathematical kernel. Returns a pure Python tuple of
    NumPy arrays to ensure faultless boxing cross compiler boundaries.
    """
    valid_mask = np.isfinite(t) & np.isfinite(y)
    t_v = t[valid_mask]
    y_v = y[valid_mask]
    
    sort_idx = np.argsort(t_v)
    t_s = t_v[sort_idx]
    y_s = y_v[sort_idx]
    
    if align_t0:
        t0 = t_s[0]
    else:
        t0 = np.floor(t_s[0] / t_sec) * t_sec
        
    b = np.floor((t_s - t0) / t_sec).astype(np.int32)
    bmin = b[0]
    bmax = b[-1]
    nb = bmax - bmin + 1
    
    sumy = np.zeros(nb)
    cnt = np.zeros(nb)
    
    for idx in range(len(b)):
        bin_id = b[idx] - bmin
        sumy[bin_id] += y_s[idx]
        cnt[bin_id] += 1.0
        
    tL = t0 + (np.arange(bmin, bmax + 1)) * t_sec
    keep = cnt > 0
    
    t_center = tL[keep] + t_sec / 2.0
    pd_mean = sumy[keep] / cnt[keep]
    left_edges = tL[keep]
    
    return t_center, pd_mean, left_edges


def downsample_block_mean(t: np.ndarray, y: np.ndarray, t_sec: int, align: str = 't0') -> dict:
    """
    Public un-jitted Python shell. Resolves string parsing limits and constructs
    the output dictionary directly in standard Python memory space.
    """
    align_t0 = (align == 't0')
    # Trigger the JIT worker and collect raw tuples
    t_center, pd_mean, left_edges = _downsample_block_mean_worker(t, y, t_sec, align_t0)
    
    return {
        't': t_center,
        'Pd': pd_mean,
        'left_edges': left_edges,
        'Tsec': t_sec
    }


@njit(cache=True)
def _fit_dtmc_worker(power_samples: np.ndarray, m_states: int, alpha: float):
    """
    Private JIT-compiled kernel tracking matrix probabilities and solver systems.
    Returns array blocks as a clean tuple to maintain architectural consistency.
    """
    x = power_samples.flatten()
    if len(x) < 3:
        raise ValueError("Insufficient sample count to train a valid Markov chain.")
        
    edges = _make_edges_quantile_numba(x, m_states)
    
    S = np.zeros(len(x), dtype=np.int32)
    for idx in range(len(x)):
        val = x[idx]
        bin_idx = m_states - 1 
        for b_idx in range(m_states):
            if val >= edges[b_idx] and val < edges[b_idx+1]:
                bin_idx = b_idx
                break
        S[idx] = bin_idx
        
    N = np.zeros((m_states, m_states))
    for idx in range(len(S) - 1):
        N[S[idx], S[idx+1]] += 1.0
        
    P = N + alpha
    for r_idx in range(m_states):
        row_sum = np.sum(P[r_idx, :])
        if row_sum == 0:
            P[r_idx, :] = 1.0 / m_states
        else:
            P[r_idx, :] = P[r_idx, :] / row_sum
            
    A = np.zeros((m_states + 1, m_states))
    A[:m_states, :] = P.T - np.eye(m_states)
    A[m_states, :] = 1.0
    
    b_vec = np.zeros(m_states + 1)
    b_vec[m_states] = 1.0
    
    ATA = A.T @ A
    ATb = A.T @ b_vec
    stationary_pi = np.linalg.solve(ATA, ATb)
    
    levels = np.zeros(m_states)
    for idx in range(m_states):
        levels[idx] = (edges[idx] + edges[idx+1]) / 2.0
        
    return P, N, stationary_pi, edges, levels, S + 1


def fit_dtmc(power_samples: np.ndarray, m_states: int, alpha: float = 0.5) -> dict:
    """
    Public Python shell wrapping the DTMC calibration data arrays into a dict.
    """
    P, N, stationary_pi, edges, levels, S_1indexed = _fit_dtmc_worker(power_samples, m_states, alpha)
    
    return {
        'P': P,
        'N': N,
        'pi': stationary_pi,
        'edges': edges,
        'levels': levels,
        'S': S_1indexed
    }